name: scrollviewproj
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/scrollviewproj/assets/images/1_168.png
    - packages/scrollviewproj/assets/images/1_171.png
    - packages/scrollviewproj/assets/images/I1_255;1_175.png
    - packages/scrollviewproj/assets/images/I1_255;1_174.png
    - packages/scrollviewproj/assets/images/I1_255;1_173.png
    - packages/scrollviewproj/assets/images/I1_255;1_172.png
    - packages/scrollviewproj/assets/images/I1_255;1_168.png
    - packages/scrollviewproj/assets/images/I1_271;1_175.png
    - packages/scrollviewproj/assets/images/I1_271;1_174.png
    - packages/scrollviewproj/assets/images/I1_271;1_173.png
    - packages/scrollviewproj/assets/images/I1_271;1_172.png
    - packages/scrollviewproj/assets/images/I1_271;1_168.png
    - packages/scrollviewproj/assets/images/I1_288;1_175.png
    - packages/scrollviewproj/assets/images/I1_288;1_174.png
    - packages/scrollviewproj/assets/images/I1_288;1_173.png
    - packages/scrollviewproj/assets/images/I1_288;1_172.png
    - packages/scrollviewproj/assets/images/I1_288;1_168.png
    - packages/scrollviewproj/assets/images/I1_304;1_175.png
    - packages/scrollviewproj/assets/images/I1_304;1_174.png
    - packages/scrollviewproj/assets/images/I1_304;1_173.png
    - packages/scrollviewproj/assets/images/I1_304;1_172.png
    - packages/scrollviewproj/assets/images/I1_304;1_168.png
    - packages/scrollviewproj/assets/images/I1_320;1_175.png
    - packages/scrollviewproj/assets/images/I1_320;1_174.png
    - packages/scrollviewproj/assets/images/I1_320;1_173.png
    - packages/scrollviewproj/assets/images/I1_320;1_172.png
    - packages/scrollviewproj/assets/images/I1_320;1_168.png
    - packages/scrollviewproj/assets/images/I1_369;1_175.png
    - packages/scrollviewproj/assets/images/I1_369;1_174.png
    - packages/scrollviewproj/assets/images/I1_369;1_173.png
    - packages/scrollviewproj/assets/images/I1_369;1_172.png
    - packages/scrollviewproj/assets/images/I1_369;1_168.png
    - packages/scrollviewproj/assets/images/I1_385;1_175.png
    - packages/scrollviewproj/assets/images/I1_385;1_174.png
    - packages/scrollviewproj/assets/images/I1_385;1_173.png
    - packages/scrollviewproj/assets/images/I1_385;1_172.png
    - packages/scrollviewproj/assets/images/I1_385;1_168.png
    - packages/scrollviewproj/assets/images/I1_401;1_175.png
    - packages/scrollviewproj/assets/images/I1_401;1_174.png
    - packages/scrollviewproj/assets/images/I1_401;1_173.png
    - packages/scrollviewproj/assets/images/I1_401;1_172.png
    - packages/scrollviewproj/assets/images/I1_401;1_168.png
    - packages/scrollviewproj/assets/images/I1_417;1_175.png
    - packages/scrollviewproj/assets/images/I1_417;1_174.png
    - packages/scrollviewproj/assets/images/I1_417;1_173.png
    - packages/scrollviewproj/assets/images/I1_417;1_172.png
    - packages/scrollviewproj/assets/images/I1_417;1_168.png
    - packages/scrollviewproj/assets/images/I1_433;1_175.png
    - packages/scrollviewproj/assets/images/I1_433;1_174.png
    - packages/scrollviewproj/assets/images/I1_433;1_173.png
    - packages/scrollviewproj/assets/images/I1_433;1_172.png
    - packages/scrollviewproj/assets/images/I1_433;1_168.png
    - packages/scrollviewproj/assets/images/I1_449;1_175.png
    - packages/scrollviewproj/assets/images/I1_449;1_174.png
    - packages/scrollviewproj/assets/images/I1_449;1_173.png
    - packages/scrollviewproj/assets/images/I1_449;1_172.png
    - packages/scrollviewproj/assets/images/I1_449;1_168.png
    - packages/scrollviewproj/assets/images/I1_465;1_175.png
    - packages/scrollviewproj/assets/images/I1_465;1_174.png
    - packages/scrollviewproj/assets/images/I1_465;1_173.png
    - packages/scrollviewproj/assets/images/I1_465;1_172.png
    - packages/scrollviewproj/assets/images/I1_465;1_168.png
    - packages/scrollviewproj/assets/images/1_168.png
    - packages/scrollviewproj/assets/images/1_171.png
    - packages/scrollviewproj/assets/images/I1_255;1_175.png
    - packages/scrollviewproj/assets/images/I1_255;1_174.png
    - packages/scrollviewproj/assets/images/I1_255;1_173.png
    - packages/scrollviewproj/assets/images/I1_255;1_172.png
    - packages/scrollviewproj/assets/images/I1_255;1_168.png
    - packages/scrollviewproj/assets/images/I1_271;1_175.png
    - packages/scrollviewproj/assets/images/I1_271;1_174.png
    - packages/scrollviewproj/assets/images/I1_271;1_173.png
    - packages/scrollviewproj/assets/images/I1_271;1_172.png
    - packages/scrollviewproj/assets/images/I1_271;1_168.png
    - packages/scrollviewproj/assets/images/I1_288;1_175.png
    - packages/scrollviewproj/assets/images/I1_288;1_174.png
    - packages/scrollviewproj/assets/images/I1_288;1_173.png
    - packages/scrollviewproj/assets/images/I1_288;1_172.png
    - packages/scrollviewproj/assets/images/I1_288;1_168.png
    - packages/scrollviewproj/assets/images/I1_304;1_175.png
    - packages/scrollviewproj/assets/images/I1_304;1_174.png
    - packages/scrollviewproj/assets/images/I1_304;1_173.png
    - packages/scrollviewproj/assets/images/I1_304;1_172.png
    - packages/scrollviewproj/assets/images/I1_304;1_168.png
    - packages/scrollviewproj/assets/images/I1_320;1_175.png
    - packages/scrollviewproj/assets/images/I1_320;1_174.png
    - packages/scrollviewproj/assets/images/I1_320;1_173.png
    - packages/scrollviewproj/assets/images/I1_320;1_172.png
    - packages/scrollviewproj/assets/images/I1_320;1_168.png
    - packages/scrollviewproj/assets/images/I1_369;1_175.png
    - packages/scrollviewproj/assets/images/I1_369;1_174.png
    - packages/scrollviewproj/assets/images/I1_369;1_173.png
    - packages/scrollviewproj/assets/images/I1_369;1_172.png
    - packages/scrollviewproj/assets/images/I1_369;1_168.png
    - packages/scrollviewproj/assets/images/I1_385;1_175.png
    - packages/scrollviewproj/assets/images/I1_385;1_174.png
    - packages/scrollviewproj/assets/images/I1_385;1_173.png
    - packages/scrollviewproj/assets/images/I1_385;1_172.png
    - packages/scrollviewproj/assets/images/I1_385;1_168.png
    - packages/scrollviewproj/assets/images/I1_401;1_175.png
    - packages/scrollviewproj/assets/images/I1_401;1_174.png
    - packages/scrollviewproj/assets/images/I1_401;1_173.png
    - packages/scrollviewproj/assets/images/I1_401;1_172.png
    - packages/scrollviewproj/assets/images/I1_401;1_168.png
    - packages/scrollviewproj/assets/images/I1_417;1_175.png
    - packages/scrollviewproj/assets/images/I1_417;1_174.png
    - packages/scrollviewproj/assets/images/I1_417;1_173.png
    - packages/scrollviewproj/assets/images/I1_417;1_172.png
    - packages/scrollviewproj/assets/images/I1_417;1_168.png
    - packages/scrollviewproj/assets/images/I1_433;1_175.png
    - packages/scrollviewproj/assets/images/I1_433;1_174.png
    - packages/scrollviewproj/assets/images/I1_433;1_173.png
    - packages/scrollviewproj/assets/images/I1_433;1_172.png
    - packages/scrollviewproj/assets/images/I1_433;1_168.png
    - packages/scrollviewproj/assets/images/I1_449;1_175.png
    - packages/scrollviewproj/assets/images/I1_449;1_174.png
    - packages/scrollviewproj/assets/images/I1_449;1_173.png
    - packages/scrollviewproj/assets/images/I1_449;1_172.png
    - packages/scrollviewproj/assets/images/I1_449;1_168.png
    - packages/scrollviewproj/assets/images/I1_465;1_175.png
    - packages/scrollviewproj/assets/images/I1_465;1_174.png
    - packages/scrollviewproj/assets/images/I1_465;1_173.png
    - packages/scrollviewproj/assets/images/I1_465;1_172.png
    - packages/scrollviewproj/assets/images/I1_465;1_168.png
    - packages/scrollviewproj/assets/images/1_168.png
    - packages/scrollviewproj/assets/images/1_171.png
    - packages/scrollviewproj/assets/images/I1_255;1_175.png
    - packages/scrollviewproj/assets/images/I1_255;1_174.png
    - packages/scrollviewproj/assets/images/I1_255;1_173.png
    - packages/scrollviewproj/assets/images/I1_255;1_172.png
    - packages/scrollviewproj/assets/images/I1_255;1_168.png
    - packages/scrollviewproj/assets/images/I1_271;1_175.png
    - packages/scrollviewproj/assets/images/I1_271;1_174.png
    - packages/scrollviewproj/assets/images/I1_271;1_173.png
    - packages/scrollviewproj/assets/images/I1_271;1_172.png
    - packages/scrollviewproj/assets/images/I1_271;1_168.png
    - packages/scrollviewproj/assets/images/I1_288;1_175.png
    - packages/scrollviewproj/assets/images/I1_288;1_174.png
    - packages/scrollviewproj/assets/images/I1_288;1_173.png
    - packages/scrollviewproj/assets/images/I1_288;1_172.png
    - packages/scrollviewproj/assets/images/I1_288;1_168.png
    - packages/scrollviewproj/assets/images/I1_304;1_175.png
    - packages/scrollviewproj/assets/images/I1_304;1_174.png
    - packages/scrollviewproj/assets/images/I1_304;1_173.png
    - packages/scrollviewproj/assets/images/I1_304;1_172.png
    - packages/scrollviewproj/assets/images/I1_304;1_168.png
    - packages/scrollviewproj/assets/images/I1_320;1_175.png
    - packages/scrollviewproj/assets/images/I1_320;1_174.png
    - packages/scrollviewproj/assets/images/I1_320;1_173.png
    - packages/scrollviewproj/assets/images/I1_320;1_172.png
    - packages/scrollviewproj/assets/images/I1_320;1_168.png
    - packages/scrollviewproj/assets/images/I1_369;1_175.png
    - packages/scrollviewproj/assets/images/I1_369;1_174.png
    - packages/scrollviewproj/assets/images/I1_369;1_173.png
    - packages/scrollviewproj/assets/images/I1_369;1_172.png
    - packages/scrollviewproj/assets/images/I1_369;1_168.png
    - packages/scrollviewproj/assets/images/I1_385;1_175.png
    - packages/scrollviewproj/assets/images/I1_385;1_174.png
    - packages/scrollviewproj/assets/images/I1_385;1_173.png
    - packages/scrollviewproj/assets/images/I1_385;1_172.png
    - packages/scrollviewproj/assets/images/I1_385;1_168.png
    - packages/scrollviewproj/assets/images/I1_401;1_175.png
    - packages/scrollviewproj/assets/images/I1_401;1_174.png
    - packages/scrollviewproj/assets/images/I1_401;1_173.png
    - packages/scrollviewproj/assets/images/I1_401;1_172.png
    - packages/scrollviewproj/assets/images/I1_401;1_168.png
    - packages/scrollviewproj/assets/images/I1_417;1_175.png
    - packages/scrollviewproj/assets/images/I1_417;1_174.png
    - packages/scrollviewproj/assets/images/I1_417;1_173.png
    - packages/scrollviewproj/assets/images/I1_417;1_172.png
    - packages/scrollviewproj/assets/images/I1_417;1_168.png
    - packages/scrollviewproj/assets/images/I1_433;1_175.png
    - packages/scrollviewproj/assets/images/I1_433;1_174.png
    - packages/scrollviewproj/assets/images/I1_433;1_173.png
    - packages/scrollviewproj/assets/images/I1_433;1_172.png
    - packages/scrollviewproj/assets/images/I1_433;1_168.png
    - packages/scrollviewproj/assets/images/I1_449;1_175.png
    - packages/scrollviewproj/assets/images/I1_449;1_174.png
    - packages/scrollviewproj/assets/images/I1_449;1_173.png
    - packages/scrollviewproj/assets/images/I1_449;1_172.png
    - packages/scrollviewproj/assets/images/I1_449;1_168.png
    - packages/scrollviewproj/assets/images/I1_465;1_175.png
    - packages/scrollviewproj/assets/images/I1_465;1_174.png
    - packages/scrollviewproj/assets/images/I1_465;1_173.png
    - packages/scrollviewproj/assets/images/I1_465;1_172.png
    - packages/scrollviewproj/assets/images/I1_465;1_168.png
    - packages/scrollviewproj/assets/images/1_168.png
    - packages/scrollviewproj/assets/images/1_171.png
    - packages/scrollviewproj/assets/images/I1_255;1_175.png
    - packages/scrollviewproj/assets/images/I1_255;1_174.png
    - packages/scrollviewproj/assets/images/I1_255;1_173.png
    - packages/scrollviewproj/assets/images/I1_255;1_172.png
    - packages/scrollviewproj/assets/images/I1_255;1_168.png
    - packages/scrollviewproj/assets/images/I1_271;1_175.png
    - packages/scrollviewproj/assets/images/I1_271;1_174.png
    - packages/scrollviewproj/assets/images/I1_271;1_173.png
    - packages/scrollviewproj/assets/images/I1_271;1_172.png
    - packages/scrollviewproj/assets/images/I1_271;1_168.png
    - packages/scrollviewproj/assets/images/I1_288;1_175.png
    - packages/scrollviewproj/assets/images/I1_288;1_174.png
    - packages/scrollviewproj/assets/images/I1_288;1_173.png
    - packages/scrollviewproj/assets/images/I1_288;1_172.png
    - packages/scrollviewproj/assets/images/I1_288;1_168.png
    - packages/scrollviewproj/assets/images/I1_304;1_175.png
    - packages/scrollviewproj/assets/images/I1_304;1_174.png
    - packages/scrollviewproj/assets/images/I1_304;1_173.png
    - packages/scrollviewproj/assets/images/I1_304;1_172.png
    - packages/scrollviewproj/assets/images/I1_304;1_168.png
    - packages/scrollviewproj/assets/images/I1_320;1_175.png
    - packages/scrollviewproj/assets/images/I1_320;1_174.png
    - packages/scrollviewproj/assets/images/I1_320;1_173.png
    - packages/scrollviewproj/assets/images/I1_320;1_172.png
    - packages/scrollviewproj/assets/images/I1_320;1_168.png
    - packages/scrollviewproj/assets/images/I1_369;1_175.png
    - packages/scrollviewproj/assets/images/I1_369;1_174.png
    - packages/scrollviewproj/assets/images/I1_369;1_173.png
    - packages/scrollviewproj/assets/images/I1_369;1_172.png
    - packages/scrollviewproj/assets/images/I1_369;1_168.png
    - packages/scrollviewproj/assets/images/I1_385;1_175.png
    - packages/scrollviewproj/assets/images/I1_385;1_174.png
    - packages/scrollviewproj/assets/images/I1_385;1_173.png
    - packages/scrollviewproj/assets/images/I1_385;1_172.png
    - packages/scrollviewproj/assets/images/I1_385;1_168.png
    - packages/scrollviewproj/assets/images/I1_401;1_175.png
    - packages/scrollviewproj/assets/images/I1_401;1_174.png
    - packages/scrollviewproj/assets/images/I1_401;1_173.png
    - packages/scrollviewproj/assets/images/I1_401;1_172.png
    - packages/scrollviewproj/assets/images/I1_401;1_168.png
    - packages/scrollviewproj/assets/images/I1_417;1_175.png
    - packages/scrollviewproj/assets/images/I1_417;1_174.png
    - packages/scrollviewproj/assets/images/I1_417;1_173.png
    - packages/scrollviewproj/assets/images/I1_417;1_172.png
    - packages/scrollviewproj/assets/images/I1_417;1_168.png
    - packages/scrollviewproj/assets/images/I1_433;1_175.png
    - packages/scrollviewproj/assets/images/I1_433;1_174.png
    - packages/scrollviewproj/assets/images/I1_433;1_173.png
    - packages/scrollviewproj/assets/images/I1_433;1_172.png
    - packages/scrollviewproj/assets/images/I1_433;1_168.png
    - packages/scrollviewproj/assets/images/I1_449;1_175.png
    - packages/scrollviewproj/assets/images/I1_449;1_174.png
    - packages/scrollviewproj/assets/images/I1_449;1_173.png
    - packages/scrollviewproj/assets/images/I1_449;1_172.png
    - packages/scrollviewproj/assets/images/I1_449;1_168.png
    - packages/scrollviewproj/assets/images/I1_465;1_175.png
    - packages/scrollviewproj/assets/images/I1_465;1_174.png
    - packages/scrollviewproj/assets/images/I1_465;1_173.png
    - packages/scrollviewproj/assets/images/I1_465;1_172.png
    - packages/scrollviewproj/assets/images/I1_465;1_168.png
